name: "GKE Kubeconfig"
description: "Generate different Kubeconfig formats compatible with GKE."
inputs:
  useAuthProvider:
    description: "If true, use an authentication provider to authenticate to GKE"
    required: false
    default: "true"
  gkeCredentials:
    description: "GKE credentials used to create GKE clusters. Optional if GKE clusters are not required"
    required: false
  clusterName:
    description: "Cluster to get credentials for"
    required: true
  location:
    description: "Region or zone where the cluster is located"
    required: true
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gkeCredentials }}
        create_credentials_file: true
    - name: Install gke-gcloud-auth-plugin
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: gke-gcloud-auth-plugin
