name: "Provision EC2 Runner"
description: "Provision a GitHub Action runner in AWS"
inputs: 
  aws_access_key_id: 
    description: 'Use a secret - this account needs "ec2-admin" permissions'
    required: true
  aws_secret_access_key: 
    description: 'Use a secret - this account needs "ec2-admin" permissions'
    required: true
  github_token: 
    description: "Use a secret. Token used to register a github action runner. If D6E Automaton token make sure it is added to the repo with Admin powers."
    required: true
  region: 
    description: 'aws region for the runner. Default us-east-1'
    required: false
    default: 'us-east-1'
  ami_id: 
    description: "ami ID that will run on the mac2 instance. Must be associated with the Host Resource Group license."
    required: false
    default: 'ami-071cf1597857cbcc8'
  instance_type: 
    description: "the instance type to spin up in the Host Resource Group"
    required: true
    default: 'mac2.metal'
  host_resource_group_arn: 
    description: "the arn of the HRG that will automate setup of the dedicated hosts for the runners"
    required: false
    default: "arn:aws:resource-groups:us-east-1:914373874199:group/GitHub-Runners"
  github_runner_installer:
    description: "the url of the tar archive for the github runner installer. Must match desired instance architecture"
    required: true
    default: https://github.com/actions/runner/releases/download/v2.298.2/actions-runner-osx-arm64-2.298.2.tar.gz
  
  
runs: 
  using: 'composite'
  steps: 
  - name: "Prepare GitHub Runner Token"
    uses: docker://ubuntu:22.04
    run: setup-runner.sh
    shell: bash