name: "Provision EC2 Runner"
description: "Provision a GitHub Action runner in AWS"
inputs: 
  aws_access_key_id: 
    description: 'Use a secret - this account needs "ec2-admin" permissions'
    required: true
  aws_secret_access_key: 
    description: 'Use a secret - this account needs "ec2-admin" permissions'
    required: true
  runner_admin_token: 
    description: "Use a secret. Token used to register a github action runner. If D6E Automaton token make sure it is added to the repo with Admin powers."
    required: true
  region: 
    description: 'aws region for the runner. Default us-east-1'
    required: false
    default: 'us-east-1'
  ami_id: 
    description: "ami ID that will run on the mac2 instance. Must be associated with the Host Resource Group license."
    required: false
    default: 'ami-071cf1597857cbcc8'
  ami_home_directory:
    description: "the home directory for users on this AMI. Ex: /home"
    required: true
    default: /home
  ami_user: 
    description: "the automatically configured user on the ami. Usually ec2-user"
    required: false
    default: "ec2-user"
  instance_type: 
    description: "the instance type to spin up in the Host Resource Group"
    required: true
    default: 'mac2.metal'
  host_resource_group_arn: 
    description: "the arn of the HRG that will automate setup of the dedicated hosts for the runners"
    required: false
    default: ""
  github_runner_installer:
    description: "the url of the tar archive for the github runner installer. Must match desired instance architecture"
    required: true
    default: https://github.com/actions/runner/releases/download/v2.298.2/actions-runner-osx-arm64-2.298.2.tar.gz
  runner_labels: 
    description: "labels to add when registering the runner Ex: \"m1_mac\". Use this label in the `runs-on` section of the jobs."
    required: false
  
runs: 
  using: 'composite'
  steps: 
  - name: "Prepare GitHub Runner"
    run: $GITHUB_ACTION_PATH/setup-runner.sh
    shell: bash
    env: 
      GITHUB_REPOSITORY: ${{ github.repository }}
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      AWS_DEFAULT_REGION: ${{ inputs.region }}
      RUNNER_ADMIN_TOKEN: ${{ inputs.runner_admin_token }} 
      AMI_ID: ${{ inputs.ami_id }}
      AMI_USER: ${{ inputs.ami_user }}
      AMI_HOME: ${{ inputs.ami_home }}
      INSTANCE_TYPE: ${{ inputs.instance_type }}
      GITHUB_RUNNER_INSTALLER: ${{ inputs.github_runner_installer }}
      HOST_RESOURCE_GROUP_ARN: ${{ inputs.host_resource_group_arn }}
      RUNNER_LABELS: ${{ inputs.runner_labels }}