# Stage 1: Compile Go target
FROM golang:1.18 as builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Stage 2: Set up Ubuntu 22.04 image
FROM ubuntu:22.04

WORKDIR /root/

RUN apt-get update && apt-get install -y ca-certificates openssl
ENV SSL_CERT_DIR=/etc/ssl/certs

# Copy the pre-built binary from the previous stage.
COPY --from=builder /app/main .

# Command to run the executable
CMD ["./main"]
