## Mapping
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  annotations: {}
  name: github-runner-provisioner
spec:
  host: sw.bakerstreet.io
  prefix: /github-runner-provisioner/
  rewrite: ""
  service: github-runner-provisioner:80
  timeout_ms: 60000

## Service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    a8r.io/chat: '#team-infra'
    a8r.io/description: "Mac M1 provisioner for GitHub jobs in Ambassador Labs repositories"
    a8r.io/logs: ""
    a8r.io/owner: Infrastructure
    a8r.io/repository: https://github.com/datawire/infra-actions
    a8r.io/runbook: ""
    a8r.io/uptime: ""
  name: github-runner-provisioner
spec:
  type: ClusterIP
  selector:
    app: github-runner-provisioner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

## Github Runner Provisioner Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-provisioner
  labels:
    app: github-runner-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner-provisioner
  template:
    metadata:
      labels:
        app: github-runner-provisioner
    spec:
      containers:
      - name: github-runner-provisioner
        image: golang:1.18.7
        imagePullPolicy: IfNotPresent
        command: ["go", "run", "."]
        workingDir: "/src"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: code-root
          mountPath: "/src"
        - name: internal-aws
          mountPath: "/src/internal/aws"
        - name: internal-monitoring
          mountPath: "/src/internal/monitoring"
        - name: internal-utils
          mountPath: "/src/internal/utils"
        env:
        - name: AWS_REGION
          value: us-east-1
        envFrom:
          - secretRef:
              name: github-runner-provisioner-secrets
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /github-runner-provisioner/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /github-runner-provisioner/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        # Provide the name of the ConfigMaps containing the files you want
        # to add to the container
        - name: code-root
          configMap:
            name: code-root
        - name: internal-aws
          configMap:
            name: internal-aws
        - name: internal-monitoring
          configMap:
            name: internal-monitoring
        - name: internal-utils
          configMap:
            name: internal-utils
        - name: github-runner-provisioner-aws-config
          secret:
            secretName: github-runner-provisioner-aws-config
