## Mapping
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  annotations: {}
  name: github-runner-provisioner
spec:
  host: sw.bakerstreet.io
  prefix: /github-runner-provisioner/
  rewrite: /github-runner-provisioner
  service: github-runner-provisioner:80
  timeout_ms: 60000

## Service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    a8r.io/chat: '#team-infra'
    a8r.io/description: "Mac M1 provisioner for GitHub jobs in Ambassador Labs repositories"
    a8r.io/logs: ""
    a8r.io/owner: Infrastructure
    a8r.io/repository: https://github.com/datawire/infra-actions
    a8r.io/runbook: ""
    a8r.io/uptime: ""
  name: github-runner-provisioner
spec:
  type: ClusterIP
  selector:
    app: github-runner-provisioner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

## Github Runner Provisioner Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-provisioner
  labels:
    app: github-runner-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner-provisioner
  template:
    metadata:
      labels:
        app: github-runner-provisioner
    spec:
      containers:
      - name: github-runner-provisioner
        image: golang:1.18.7
        imagePullPolicy: IfNotPresent
        command: ["go", "run", "."]
        workingDir: "/src"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: code
          mountPath: "/src"
        env:
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        envFrom:
          - secretRef:
              name: github-runner-provisioner-secrets
      volumes:
        - name: code
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: code
        - name: github-runner-provisioner-aws-config
          secret:
            secretName: github-runner-provisioner-aws-config
