name: "Provision Cluster"
description: "Provision a Cluster"
inputs:
  distribution:
    description: "One of GKE, AKS, EKS, OpenShift, or Kubeception"
    required: true
  noop:
    description: "If true then no cluster will be provisioned, but the action will still delete any expired clusters. Use this in a schedueled workflow to garbage collect orphaned clusters."
    required: false
  version:
    description: "The version of the cluster to create."
    required: true
  kubeconfig:
    description: "Path to the resulting kubeconfig file."
    required: true
runs:
  using: node16
  main: create.js
  post: delete.js
