name: "Provision Cluster"
description: "Provision a Cluster"
inputs:
  distribution:
    description: "One of GKE, AKS, EKS, OpenShift, or Kubeception"
    required: true
  version:
    description: "The version of the cluster to create."
    required: true
  kubeconfig:
    description: "Path to the resulting kubeconfig file."
    required: true
runs:
  using: node16
  main: create.js
  post: delete.js
