name: "Cleanup Expired Clusters"

on:
  schedule:
    - cron: '0 * * * *'

  pull_request:
    paths:
      - .github/workflows/expire.yaml

jobs:
  expire_clusters:
    strategy:
      matrix:
        distribution: [GKE]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./provision-cluster
        with:
          action: expire
          distribution: ${{ matrix.distribution }}
          kubeceptionToken: ${{ secrets.KUBECEPTION_TOKEN }}
          gkeCredentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          slackWebhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          slackChannel: "#team-infra"
          slackRunbook: "Runbook TBD"

