name: "GitHub Runner Provisioner: Tests, Builds, Deployments"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: FAKE_TOKEN
      CODEMAGIC_TOKEN: FAKE_TOKEN
      WEBHOOK_TOKEN: FAKE_TOKEN
    steps:
      - uses: actions/checkout@v2

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: cd github-runner-provisioner
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            datawiredev/github-runner-provisioner:${{ github.sha }}

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Kustomize
