name: "Telepresence Test Matrix"
on:
  pull_request:
    paths:
      - .github/workflows/matrix.yaml
      - provision-cluster/**
      - '!**/*.md'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  telepresence_matrix:
    strategy:
      matrix:

        client_os: [ubuntu]
        client_arch: [latest]

        client_telepresence_version: ["2.7"]

        clusters:
         - distribution: GKE
           version: "1.27"

         - distribution: Kubeception
           version: "1.27"

         - distribution: GKE
           version: "1.27"
           config: '{ "initialNodeCount" : 2 }'

        cluster_telepresence_version:  ["none"]

    runs-on: ${{ matrix.client_os }}-${{ matrix.client_arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          # These tests require Kubectl 1.25 or lower since 1.26+ does noe support the GCP auth plugin
          version: 'v1.25.3'
      - uses: ./provision-cluster
        with:
          distribution: ${{ matrix.clusters.distribution }}
          version: ${{ matrix.clusters.version }}
          kubeconfig: kubeconfig.yaml
          kubeceptionToken: ${{ secrets.KUBECEPTION_TOKEN }}
          gkeCredentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          gkeConfig: ${{ matrix.clusters.config }}

      - run: |
          echo Testing telepresence client version ${{ matrix.client_telepresence_version }} on ${{ matrix.client_os }} ${{ matrix.client_arch }} against server version ${{ matrix.cluster_telepresence_version }} on ${{ matrix.clusters.distribution }} cluster version ${{ matrix.clusters.version }}
          kubectl version
          kubectl get pods -A

      - name: "validate gke config"
        if: ${{ startsWith(matrix.clusters.config, '{') }}
        run: |
          nodecount=$(kubectl get nodes --no-headers | wc -l | bc)
          if [[ $nodecount == 2 ]]; then
            echo "Gke config was used!"
          else
            echo "Gke config was not used"
            exit 1
          fi
