# This github workflow is for smoke testing the latest release of the actions defined in this
# repo. This workflow is executed whenever this file is changed. That will happen when the "uses"
# line below is updated to reference the latest release as defined in the release process.

name: "Release Smoke Test"
on:
  push:
    paths:
      - '.github/workflows/smoke.yaml'
jobs:
  release_smoke:
    strategy:
      matrix:
        clusters:
         - distribution: GKE
           version: "1.23"

         - distribution: Kubeception
           version: "1.22"
    runs-on: ubuntu-latest
    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      # The provision-cluster action will automatically register a cleanup hook to remove the
      # cluster it provisions when the job is done.
      - uses: datawire/infra-actions/provision-cluster@v0.2.0
        with:
          distribution: ${{ matrix.clusters.distribution }}
          version: ${{ matrix.clusters.version }}
          kubeconfig: kubeconfig.yaml
          kubeceptionToken: ${{ secrets.KUBECEPTION_TOKEN }}
          gkeCredentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - run: |
          kubectl version
          kubectl get pods -A
