name: "Release Smoke Test"

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - '.github/workflows/smoke.yaml'

jobs:
  release_smoke_gke:
    strategy:
      fail-fast: false
      matrix:
        clusters:
         - version: "1.27"
    runs-on: ubuntu-latest
    env:
      GKE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      - id: provision
        uses: datawire/infra-actions/provision-cluster@v0.3.0
        with:
          distribution: GKE
          version: ${{ matrix.clusters.version }}
          kubeconfig: ${{ runner.temp }}/kubeconfig.yaml
          gkeCredentials: ${{ env.GKE_CREDENTIALS }}
      - name: "Get kubeconfig and cluster information"
        run: |
          set -e
          kubectl config view
          kubectl version
          kubectl get pods -A

  release_smoke_kubeception:
    strategy:
      fail-fast: false
      matrix:
        clusters:
         - version: "1.27"
    runs-on: ubuntu-latest
    env:
      KUBECEPTION_TOKEN: ${{ secrets.KUBECEPTION_TOKEN }}
    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      - id: provision
        uses: datawire/infra-actions/provision-cluster@v0.3.0
        with:
          distribution: Kubeception
          version: ${{ matrix.clusters.version }}
          kubeconfig: ${{ runner.temp }}/kubeconfig.yaml
          kubeceptionToken: ${{ env.KUBECEPTION_TOKEN }}
      - name: "Get kubeconfig and cluster information"
        run: |
          set -e
          kubectl config view
          kubectl version
          kubectl get pods -A
