name: "Release Smoke Test"

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - '.github/workflows/smoke.yaml'

jobs:
  release_smoke:
    strategy:
      fail-fast: false
      matrix:
        clusters:
         - distribution: GKE
           version: "1.27"
           useAuthProvider: "true"

         - distribution: GKE
           version: "1.27"
           useAuthProvider: "false"

         - distribution: Kubeception
           version: "1.27"
    runs-on: ubuntu-latest
    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          version: 'v1.25.3'
      - id: provision
        uses: datawire/infra-actions/provision-cluster@v0.2.6
        with:
          distribution: ${{ matrix.clusters.distribution }}
          version: ${{ matrix.clusters.version }}
          kubeconfig: ${{ runner.temp}}/kubeconfig.yaml
          kubeceptionToken: ${{ secrets.KUBECEPTION_TOKEN }}
          gkeCredentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          useAuthProvider: ${{ matrix.clusters.useAuthProvider }}
      - name: "Get kubeconfig and cluster information"
        run: |
          set -e
          kubectl config view
          kubectl version --short
          kubectl get pods -A
