name: "Testing for Action Code"

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  tests:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: .github/actions/provision-cluster
        run: npm ci
      - working-directory: .github/actions/provision-cluster
        run: npm run build --if-present
      - working-directory: .github/actions/provision-cluster
        run: npm test
